### ISSUE TITLE
Doesn't launch on Windows 7

### ISSUE THREAD

**Issue by Drskellyman** [R2Northstar/NorthstarLauncher#8] opened 2021-12-26 09:15 UTC
Exactly what the title says.  Followed the guide, compared my files to screenshots from other anons, and it just doesn't launch, giving pic related error.
![error](https://user-images.githubusercontent.com/96619022/147403881-0798ae0d-0b26-4c47-80ea-4ad6e90796de.png)
Only difference found was the operating system

**Comment by GeckoEidechse** [comment] 2022-01-01 17:24
Related to [Northstar/#65](https://github.com/R2Northstar/Northstar/issues/65).

**Comment by GeckoEidechse** [comment] 2022-01-06 20:04
Duplicate of the linked issue and it should be fixed now anyway.

**Closed** 2022-01-07 15:17 UTC
Labels: duplicate
