### ISSUE TITLE
Incorect player count on server browser.

### ISSUE THREAD

**Issue by catornot** [R2Northstar/NorthstarLauncher#314] opened 2022-10-29 02:15 UTC
I am not sure if its a ms issue.

but recently around 1.10.1 release servers had incorrect player counts in the server browser, resulting in people getting baited by a 11/12 server that is actually full.

**Comment by pg9182** [comment] 2022-10-29 13:24
#305

**Comment by GeckoEidechse** [comment] 2022-10-30 19:19
Duplicate of #305

**Closed by GeckoEidechse** 2022-10-30 19:19 UTC
